### ISSUE TITLE
AttributeError: SimpleViewClass object has no attribute 'Title'

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.namedfile#128]
Context is a tile, with this in the template:

```
<figure class="image-product"
  tal:define="scale view/@@images;
             img_tag python:scale.scale('image', scale='large').tag(css_class='img-responsive')">
  <img tal:replace="structure img_tag" />
</figure>
```

We can't ask for its Title:

```
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp39/plone.subrequest-1.9.3-py3.9.egg/plone/subrequest/__init__.py", line 154, in subrequest
    result = mapply(
  File "/Users/maurits/shared-eggs/cp39/Zope-5.5.1-py3.9.egg/ZPublisher/mapply.py", line 87, in mapply
    return object(*args)
  File "/Users/maurits/shared-eggs/cp39/plone.tiles-2.3.1-py3.9.egg/plone/tiles/tile.py", line 91, in __call__
    return self.index(*args, **kwargs)
  File "/Users/maurits/shared-eggs/cp39/Zope-5.5.1-py3.9.egg/Products/Five/browser/pagetemplatefile.py", line 126, in __call__
    return self.__func__(__self__, *args, **kw)
  File "/Users/maurits/shared-eggs/cp39/Zope-5.5.1-py3.9.egg/Products/Five/browser/pagetemplatefile.py", line 58, in __call__
    s = self.pt_render(
  File "/Users/maurits/shared-eggs/cp39/zope.pagetemplate-4.6.0-py3.9.egg/zope/pagetemplate/pagetemplate.py", line 133, in pt_render
    return self._v_program(
  File "/Users/maurits/shared-eggs/cp39/Zope-5.5.1-py3.9.egg/Products/PageTemplates/engine.py", line 365, in __call__
    return template.render(**kwargs)
  File "/Users/maurits/shared-eggs/cp39/z3c.pt-3.3.1-py3.9.egg/z3c/pt/pagetemplate.py", line 176, in render
    return base_renderer(**context)
  File "/Users/maurits/shared-eggs/cp39/Chameleon-3.9.1-py3.9.egg/chameleon/zpt/template.py", line 302, in render
    return super(PageTemplate, self).render(**_kw)
  File "/Users/maurits/shared-eggs/cp39/Chameleon-3.9.1-py3.9.egg/chameleon/template.py", line 215, in render
    raise_with_traceback(exc, tb)
  File "/Users/maurits/shared-eggs/cp39/Chameleon-3.9.1-py3.9.egg/chameleon/utils.py", line 53, in raise_with_traceback
    raise exc
  File "/Users/maurits/shared-eggs/cp39/Chameleon-3.9.1-py3.9.egg/chameleon/template.py", line 192, in render
    self._render(stream, econtext, rcontext)
  File "/Users/maurits/clients/zeelandia/plone60/var/cache/7d6e2bead38b2ed63866fc425e453f46.py", line 184, in render
    __value = _static_4624538736('python', "scale.scale('image', scale='large').tag(css_class='img-responsive')", econtext=econtext)(_static_4624538448(econtext, __zt_tmp))
  File "/Users/maurits/shared-eggs/cp39/zope.tales-5.1-py3.9.egg/zope/tales/pythonexpr.py", line 73, in __call__
    return eval(self._code, vars)
  File "<string>", line 1, in <module>
  File "/Users/maurits/clients/zeelandia/plone60/develop/plone.namedfile/plone/namedfile/scaling.py", line 126, in tag
    return ""
AttributeError: 'SimpleViewClass from /Users/maurits/clients/zeelan' object has no attribute 'Title'
```

**Comment by mauritsvanrees** [comment]
Fixed with PR #129.
